### ISSUE TITLE
Clear memory

### ISSUE THREAD

**Issue by o4061** [peterLaurence/MapView#34]
Hello, I tried the demo that you provide and I notice that any time a fragment changed the memory of the old map didn't free even when I use the destroy method. Can you give me some feedback.

**Comment by p-lr** [comment]
Hello, that's because this demo keeps into the back stack each and every navigated fragment. If you pop the back stack before navigating to a new fragment (using `navController.popBackStack()`), and if you perform a manual GC into the profiler, you'll see that the previously allocated memory is freed.
I should probably update the demo, because keeping previous fragments into the back stack isn't that helpful.

**Comment by o4061** [comment]
I think it will work, thank you
