### ISSUE TITLE
Mini gaps between tiles

### ISSUE THREAD

**Issue by dh46tw** [peterLaurence/MapView#37]
Hi, I have noticed that there are mini gaps between tiles when I zoom in/out the map, is there a way to remove these gaps? 

Here is a screenshot about the issue. 
https://imgur.com/a/OmRWyQw
https://imgur.com/a/X9t0OaG

**Comment by p-lr** [comment]
Hi, it's most likely a rendering issue rather than real gaps. There was a similar issue in MapCompose which was solved by disabling anti-alias when rendering tiles.
To test this hypothesis, I would add `it.isAntiAlias = false` L.94 of TileCanvasView.kt
Alternatively, you can fork the demo and reproduce using your tiles, so I can do the check.

**Comment by dh46tw** [comment]
Hi, I have done what you suggested, and those gaps were gone. 
Thank you for your help!
